// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: cscalist.proto

package cosmos

import (
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Params struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Linear congruential generator params
	// https://en.wikipedia.org/wiki/Linear_congruential_generator
	LcgA     uint64 `protobuf:"varint,1,opt,name=lcgA,proto3" json:"lcgA,omitempty"`
	LcgB     uint64 `protobuf:"varint,2,opt,name=lcgB,proto3" json:"lcgB,omitempty"`
	LcgMod   uint64 `protobuf:"varint,3,opt,name=lcgMod,proto3" json:"lcgMod,omitempty"`
	LcgValue uint64 `protobuf:"varint,4,opt,name=lcgValue,proto3" json:"lcgValue,omitempty"`
	// RootKey is the key of the current root node
	RootKey string `protobuf:"bytes,5,opt,name=rootKey,proto3" json:"rootKey,omitempty"`
	// RootUpdated is true when the root node was updated in Rarimo, but not in Chain
	RootUpdated bool `protobuf:"varint,6,opt,name=rootUpdated,proto3" json:"rootUpdated,omitempty"`
}

func (x *Params) Reset() {
	*x = Params{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cscalist_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Params) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Params) ProtoMessage() {}

func (x *Params) ProtoReflect() protoreflect.Message {
	mi := &file_cscalist_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Params.ProtoReflect.Descriptor instead.
func (*Params) Descriptor() ([]byte, []int) {
	return file_cscalist_proto_rawDescGZIP(), []int{0}
}

func (x *Params) GetLcgA() uint64 {
	if x != nil {
		return x.LcgA
	}
	return 0
}

func (x *Params) GetLcgB() uint64 {
	if x != nil {
		return x.LcgB
	}
	return 0
}

func (x *Params) GetLcgMod() uint64 {
	if x != nil {
		return x.LcgMod
	}
	return 0
}

func (x *Params) GetLcgValue() uint64 {
	if x != nil {
		return x.LcgValue
	}
	return 0
}

func (x *Params) GetRootKey() string {
	if x != nil {
		return x.RootKey
	}
	return ""
}

func (x *Params) GetRootUpdated() bool {
	if x != nil {
		return x.RootUpdated
	}
	return false
}

type Node struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Node self key
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Node priority (should be random)
	Priority uint64 `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"`
	// Node left son key
	Left string `protobuf:"bytes,4,opt,name=left,proto3" json:"left,omitempty"`
	// Node right son key
	Right string `protobuf:"bytes,5,opt,name=right,proto3" json:"right,omitempty"`
	// Merkle hash. H = Hash(Hash(left_key|right_key)|self_key)
	Hash string `protobuf:"bytes,6,opt,name=hash,proto3" json:"hash,omitempty"`
	// Hash(left_key|right_key)
	ChildrenHash string `protobuf:"bytes,7,opt,name=childrenHash,proto3" json:"childrenHash,omitempty"`
}

func (x *Node) Reset() {
	*x = Node{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cscalist_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_cscalist_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_cscalist_proto_rawDescGZIP(), []int{1}
}

func (x *Node) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Node) GetPriority() uint64 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Node) GetLeft() string {
	if x != nil {
		return x.Left
	}
	return ""
}

func (x *Node) GetRight() string {
	if x != nil {
		return x.Right
	}
	return ""
}

func (x *Node) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Node) GetChildrenHash() string {
	if x != nil {
		return x.ChildrenHash
	}
	return ""
}

var File_cscalist_proto protoreflect.FileDescriptor

var file_cscalist_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x63, 0x73, 0x63, 0x61, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x1a, 0x72, 0x61, 0x72, 0x69, 0x6d, 0x6f, 0x2e, 0x72, 0x61, 0x72, 0x69, 0x6d, 0x6f, 0x63,
	0x6f, 0x72, 0x65, 0x2e, 0x63, 0x73, 0x63, 0x61, 0x6c, 0x69, 0x73, 0x74, 0x1a, 0x14, 0x67, 0x6f,
	0x67, 0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xa0, 0x01, 0x0a, 0x06, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x6c, 0x63, 0x67, 0x41, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x6c, 0x63, 0x67,
	0x41, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x63, 0x67, 0x42, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x04, 0x6c, 0x63, 0x67, 0x42, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x63, 0x67, 0x4d, 0x6f, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6c, 0x63, 0x67, 0x4d, 0x6f, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x6c, 0x63, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x08, 0x6c, 0x63, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x6f, 0x6f,
	0x74, 0x4b, 0x65, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x6f, 0x6f, 0x74,
	0x4b, 0x65, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x6f, 0x6f, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x72, 0x6f, 0x6f, 0x74, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x64, 0x22, 0x96, 0x01, 0x0a, 0x04, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x12, 0x12, 0x0a, 0x04,
	0x6c, 0x65, 0x66, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x65, 0x66, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x72, 0x69, 0x67, 0x68, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x72, 0x69, 0x67, 0x68, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x68,
	0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x48, 0x61, 0x73, 0x68, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x48, 0x61, 0x73, 0x68, 0x42, 0x23,
	0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x61, 0x72,
	0x69, 0x6d, 0x6f, 0x2f, 0x6c, 0x64, 0x69, 0x66, 0x2d, 0x73, 0x64, 0x6b, 0x2f, 0x63, 0x6f, 0x73,
	0x6d, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cscalist_proto_rawDescOnce sync.Once
	file_cscalist_proto_rawDescData = file_cscalist_proto_rawDesc
)

func file_cscalist_proto_rawDescGZIP() []byte {
	file_cscalist_proto_rawDescOnce.Do(func() {
		file_cscalist_proto_rawDescData = protoimpl.X.CompressGZIP(file_cscalist_proto_rawDescData)
	})
	return file_cscalist_proto_rawDescData
}

var file_cscalist_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cscalist_proto_goTypes = []interface{}{
	(*Params)(nil), // 0: rarimo.rarimocore.cscalist.Params
	(*Node)(nil),   // 1: rarimo.rarimocore.cscalist.Node
}
var file_cscalist_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cscalist_proto_init() }
func file_cscalist_proto_init() {
	if File_cscalist_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cscalist_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Params); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cscalist_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Node); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cscalist_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cscalist_proto_goTypes,
		DependencyIndexes: file_cscalist_proto_depIdxs,
		MessageInfos:      file_cscalist_proto_msgTypes,
	}.Build()
	File_cscalist_proto = out.File
	file_cscalist_proto_rawDesc = nil
	file_cscalist_proto_goTypes = nil
	file_cscalist_proto_depIdxs = nil
}
